checkers:
  - type: http
    url: https://google.com
  - type: http
    url: https://microsoft.com
  - type: postgres
    server: mypostgres.net
    port: 5432
  - type: mysql
    server: mysql.net
    port: 3306