checkers:
  - type: http
    url: https://google.com
  - type: http
    url: https://microsoft.com
  - type: http
    url: http://localhost:8090
  - type: http
    url: https://github.com
  - type: postgres
    connectionString: host=localhost port=5433 dbname=postgres user=postgres password=superuser sslmode=disable connect_timeout=10