checkers:
  - type: http
    url: https://google.com
  - type: http
    url: https://microsoft.com
  - type: http
    url: http://localhost:8090
  - type: http
    url: https://github.com
  - type: postgres
    server: localhost
    port: 5433
  - type: mysql
    server: localhost
    port: 3306